# -*- coding: utf-8 -*-
"""week 6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WXya6mTeyL4ECPyXuSubfPefmrb_ynXE
"""

import tensorflow as tf
import numpy as np
import pathlib

# --- 1. Load a Pre-trained Lightweight Model ---
# We'll use MobileNetV2, a standard choice for Edge AI due to its size and speed.
# You would replace this section with your own trained model if you completed Step 1 (Training).

# Define input shape
input_shape = (1, 224, 224, 3) # Batch size 1, 224x224 pixels, 3 color channels

# Load the model
try:
    model = tf.keras.applications.MobileNetV2(
        weights='imagenet',
        input_shape=(224, 224, 3),
        include_top=True
    )
    print("MobileNetV2 model loaded successfully.")
except Exception as e:
    print(f"Error loading model: {e}")
    # Exit or handle error

# --- 2. Define the Representative Dataset (Crucial for Quantization) ---

# For full integer quantization, TFLite needs a small sample of your actual data
# to calculate the min/max range for the 8-bit integers.

# *** NOTE: Replace this function with a generator that loads a few hundred samples
# from your actual image dataset (e.g., your recyclable items data). ***
def representative_data_gen():
    """Generates a small dataset of input images for quantization."""
    for _ in range(100):
        # Create a dummy array matching the model's expected input shape
        data = np.random.rand(224, 224, 3).astype(np.float32)
        # Yield the data, wrapped as a list
        yield [np.expand_dims(data, axis=0)]

# --- 3. Convert the Model to TensorFlow Lite with Full Integer Quantization ---

converter = tf.lite.TFLiteConverter.from_keras_model(model)

# 3a. Enable optimizations (Full Integer Quantization)
converter.optimizations = [tf.lite.Optimize.DEFAULT]

# 3b. Set the representative dataset generator
converter.representative_dataset = representative_data_gen

# 3c. Ensure all operations are supported (fall back to float if necessary)
# This step is key to ensuring the model runs entirely on 8-bit integers.
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]

# Convert the model
tflite_model_quant = converter.convert()
print("Model conversion to TFLite (8-bit quantized) complete.")

# --- 4. Save and Analyze the Model Size ---

# Define file paths
tflite_models_dir = pathlib.Path("./tflite_models")
tflite_models_dir.mkdir(exist_ok=True)
tflite_model_file = tflite_models_dir/"quantized_mobilen